(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(Info-additional-directory-list (quote ("/Users/tommy/Library/Info")))
 '(auto-compression-mode t nil (jka-compr))
 '(bar-cursor nil)
 '(c-basic-offset 4)
 '(case-fold-search t)
 '(column-number-mode t)
 '(cperl-auto-newline t)
 '(cperl-close-paren-offset -4)
 '(cperl-electric-keywords t)
 '(cperl-electric-linefeed t)
 '(cperl-electric-parens t)
 '(cperl-indent-level 4)
 '(cperl-indent-parens-as-block t)
 '(cperl-lineup-step nil)
 '(current-language-environment "Japanese")
 '(dired-gnutar-program "tar")
 '(dired-listing-switches "-alF")
 '(dired-ls-F-marks-symlinks t)
 '(display-warning-suppressed-classes (quote (font)) t)
 '(ecb-layout-window-sizes (quote (("left8" (0.26865671641791045 . 0.463768115942029) (0.26865671641791045 . 0.2028985507246377) (0.26865671641791045 . 0.17391304347826086) (0.26865671641791045 . 0.10144927536231885)))))
 '(ecb-options-version "2.32")
 '(ecb-wget-setup (quote cons))
 '(efs-nlist-cmd "nlist -alF")
 '(efs-umask 2)
 '(fill-column 68)
 '(global-font-lock-mode t nil (font-lock))
 '(html-helper-use-expert-menu t)
 '(indent-tabs-mode nil)
 '(jde-bug-jdk-directory "/usr/java/jdk1.3")
 '(jde-build-use-make t)
 '(jde-compiler "/usr/java/jdk1.3/bin/javac")
 '(jde-db-source-directories nil)
 '(jde-enable-abbrev-mode nil)
 '(jde-imenu-enable t)
 '(jde-imenu-include-classdef t)
 '(jde-imenu-include-signature t)
 '(jde-make-program "")
 '(jde-run-java-vm "/usr/java/jdk1.3/bin/java")
 '(jde-run-java-vm-w "/usr/java/jdk1.3/bin/javaw")
 '(kill-whole-line t)
 '(list-directory-verbose-switches "-lF")
 '(mule-ucs-package t)
 '(paren-mode (quote sexp) nil (paren))
 '(query-user-mail-address nil)
 '(sgml-local-catalogs (quote ("/home/tommy/lib/psgml/CATALOG")))
 '(sgml-set-face t t)
 '(show-paren-mode t)
 '(show-trailing-whitespace t)
 '(signal-error-on-buffer-boundary nil)
 '(speedbar-frame-plist (quote (minibuffer nil width 30 border-width 0 internal-border-width 0 unsplittable t default-toolbar-visible-p nil has-modeline-p nil menubar-visible-p nil)))
 '(speedbar-tag-hierarchy-method (quote (speedbar-trim-words-tag-hierarchy speedbar-prefix-group-tag-hierarchy)))
 '(speedbar-track-mouse-flag nil)
 '(sql-oracle-program "/home/tommy/bin/rsqlplus")
 '(tab-width 4)
 '(tool-bar-mode nil)
 '(tramp-default-method "rsync")
 '(transient-mark-mode t)
 '(user-mail-address "tommy@imjp.co.jp")
 '(utf-translate-cjk-mode t)
 '(w3m-display-inline-image t)
 '(w3m-form-input-textarea-buffer-lines 20)
 '(w3m-home-page "http://desk.imjp.co.jp/wiki/wiki.cgi/tommy")
 '(w3m-key-binding (quote info))
 '(w3m-use-mule-ucs t)
 '(xrdb-subdivide-by (quote buffer)))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:background "#00002A" :foreground "white"))))
 '(cperl-hash-face ((((class color) (background light)) (:foreground "dark red" :bold t))) t)
 '(cperl-here-face ((((type x) (class color)) (:foreground "green4" :background "palegoldenrod"))))
 '(cperl-nonoverridable-face ((((class color) (background light)) (:foreground "dark orchid"))) t)
 '(cursor ((t (:background "white" :foreground "black"))))
 '(diff-added ((t (:inherit diff-changed :background "#CCCCFF"))))
 '(diff-changed ((nil (:background "#99FF99"))))
 '(diff-file-header ((((class color) (min-colors 88) (background light)) (:background "DarkBlue" :foreground "white" :weight bold))))
 '(diff-hunk-header ((t (:inherit diff-header :background "lightgoldenrod"))))
 '(diff-removed ((t (:inherit diff-changed :background "#FF9999"))))
 '(dired-face-directory ((t (:foreground "mediumblue" :background "#DDEEEE" :bold t))))
 '(dired-face-executable ((((class color)) (:foreground "SeaGreen" :background "#DDEEDD" :bold t))))
 '(dired-face-permissions ((t (:foreground "black" :background "lavender"))))
 '(dired-face-symlink ((((class color)) (:foreground "mediumblue" :underline t))))
 '(font-lock-comment-face ((nil (:foreground "#D90000"))))
 '(font-lock-function-name-face ((nil (:foreground "#D3C712"))))
 '(font-lock-keyword-face ((nil (:foreground "#7386FD"))))
 '(font-lock-other-type-face ((t (:foreground "darkred"))))
 '(font-lock-preprocessor-face ((((class color) (background light)) (:foreground "mediumblue" :background "powderblue"))))
 '(font-lock-reference-face ((((class color) (background light)) (:foreground "royalblue"))))
 '(font-lock-string-face ((nil (:foreground "#00C817"))))
 '(font-lock-type-face ((nil (:foreground "#7CFB88"))))
 '(font-lock-variable-name-face ((nil (:foreground "#D11FC9"))))
 '(gui-button-face ((t (:background "grey85" :inverse-video t))))
 '(info-node ((t (:foreground "blue" :background "pink2" :bold t :underline t))))
 '(info-xref ((t (:foreground "blue" :bold t))))
 '(message-url ((t (:foreground "blue" :italic t))))
 '(mew-face-body-cite1 ((((class color) (type tty)) (:foreground "green")) (((class color) (background light)) (:foreground "ForestGreen")) (((class color) (background dark)) (:foreground "LimeGreen")) (t nil)) t)
 '(mew-face-body-cite2 ((((class color) (type tty)) (:foreground "cyan")) (((class color) (background light)) (:foreground "MediumBlue")) (((class color) (background dark)) (:foreground "SkyBlue")) (t nil)) t)
 '(mew-face-body-cite3 ((((class color) (type tty)) (:foreground "magenta")) (((class color) (background light)) (:foreground "DarkViolet")) (((class color) (background dark)) (:foreground "violet")) (t nil)) t)
 '(mew-face-body-cite4 ((((class color) (type tty)) (:foreground "yellow")) (((class color) (background light)) (:foreground "DarkOrange4")) (((class color) (background dark)) (:foreground "Gold")) (t nil)) t)
 '(mew-face-body-cite5 ((((class color) (type tty)) (:foreground "red")) (((class color) (background light)) (:foreground "Firebrick")) (((class color) (background dark)) (:foreground "OrangeRed")) (t nil)) t)
 '(mew-face-body-comment ((((class color) (type tty)) (:foreground "blue")) (((class color) (background light)) (:foreground "gray50")) (((class color) (background dark)) (:foreground "gray50")) (t nil)) t)
 '(mew-face-body-url ((((class color) (type tty)) (:foreground "red" :bold t)) (((class color) (background light)) (:foreground "Firebrick" :bold t)) (((class color) (background dark)) (:foreground "OrangeRed" :bold t)) (t (:bold t))) t)
 '(mew-face-eof-message ((((class color) (type tty)) (:foreground "green" :bold t)) (((class color) (background light)) (:foreground "ForestGreen" :bold t)) (((class color) (background dark)) (:foreground "LimeGreen" :bold t)) (t (:bold t))) t)
 '(mew-face-eof-part ((((class color) (type tty)) (:foreground "yellow" :bold t)) (((class color) (background light)) (:foreground "DarkOrange4" :bold t)) (((class color) (background dark)) (:foreground "Gold" :bold t)) (t (:bold t))) t)
 '(mew-face-header-date ((((class color) (type tty)) (:foreground "green" :bold t)) (((class color) (background light)) (:foreground "ForestGreen" :bold t)) (((class color) (background dark)) (:foreground "LimeGreen" :bold t)) (t (:bold t))) t)
 '(mew-face-header-from ((((class color) (type tty)) (:foreground "yellow" :bold t)) (((class color) (background light)) (:foreground "DarkOrange4" :bold t)) (((class color) (background dark)) (:foreground "Gold" :bold t)) (t (:bold t))) t)
 '(mew-face-header-important ((((class color) (type tty)) (:foreground "cyan" :bold t)) (((class color) (background light)) (:foreground "MediumBlue" :bold t)) (((class color) (background dark)) (:foreground "SkyBlue" :bold t)) (t (:bold t))) t)
 '(mew-face-header-key ((((class color) (type tty)) (:foreground "green" :bold t)) (((class color) (background light)) (:foreground "ForestGreen" :bold t)) (((class color) (background dark)) (:foreground "LimeGreen" :bold t)) (t (:bold t))) t)
 '(mew-face-header-marginal ((((class color) (type tty)) (:bold t)) (((class color) (background light)) (:foreground "gray50" :bold t)) (((class color) (background dark)) (:foreground "gray50" :bold t)) (t (:bold t))) t)
 '(mew-face-header-private ((((class color) (type tty)) (:bold t)) (((class color) (background light)) (:bold t)) (((class color) (background dark)) (:bold t)) (t (:bold t))) t)
 '(mew-face-header-subject ((((class color) (type tty)) (:foreground "red" :bold t)) (((class color) (background light)) (:foreground "Firebrick" :bold t)) (((class color) (background dark)) (:foreground "OrangeRed" :bold t)) (t (:bold t))) t)
 '(mew-face-header-to ((((class color) (type tty)) (:foreground "magenta" :bold t)) (((class color) (background light)) (:foreground "DarkViolet" :bold t)) (((class color) (background dark)) (:foreground "violet" :bold t)) (t (:bold t))) t)
 '(mew-face-header-xmew ((((class color) (type tty)) (:foreground "yellow" :bold t)) (((class color) (background light)) (:foreground "chocolate" :bold t)) (((class color) (background dark)) (:foreground "chocolate" :bold t)) (t (:bold t))) t)
 '(mew-face-header-xmew-bad ((((class color) (type tty)) (:foreground "red" :bold t)) (((class color) (background light)) (:foreground "red" :bold t)) (((class color) (background dark)) (:foreground "red" :bold t)) (t (:bold t))) t)
 '(mew-face-mark-delete ((((class color) (type tty)) (:foreground "red")) (((class color) (background light)) (:foreground "Firebrick")) (((class color) (background dark)) (:foreground "OrangeRed")) (t (:bold t))) t)
 '(mew-face-mark-multi ((((class color) (type tty)) (:foreground "magenta")) (((class color) (background light)) (:foreground "DarkViolet")) (((class color) (background dark)) (:foreground "violet")) (t (:bold t))) t)
 '(mew-face-mark-refile ((((class color) (type tty)) (:foreground "green")) (((class color) (background light)) (:foreground "ForestGreen")) (((class color) (background dark)) (:foreground "LimeGreen")) (t (:bold t))) t)
 '(mew-face-mark-review ((((class color) (type tty)) (:foreground "cyan")) (((class color) (background light)) (:foreground "MediumBlue")) (((class color) (background dark)) (:foreground "SkyBlue")) (t (:bold t))) t)
 '(mew-face-mark-unlink ((((class color) (type tty)) (:foreground "yellow")) (((class color) (background light)) (:foreground "DarkOrange4")) (((class color) (background dark)) (:foreground "Gold")) (t (:bold t))) t)
 '(mew-highlight-body-face-quote ((t (:foreground "ForestGreen" :background "#DDEEDD"))))
 '(mew-highlight-header-face-from ((t (:foreground "Purple" :background "#EEDDFF" :bold t))))
 '(mew-highlight-header-face-important ((t (:foreground "Blue" :background "#DDDDDD" :bold t))))
 '(mew-highlight-header-face-key ((t (:foreground "ForestGreen" :bold t))))
 '(mew-highlight-header-face-marginal ((t (:foreground "gray40"))))
 '(mew-highlight-header-face-private ((t (:background "#DDDDDD"))))
 '(mew-highlight-header-face-subject ((t (:foreground "firebrick" :background "#EEDDDD" :bold t))))
 '(mew-highlight-header-face-to ((t (:foreground "OrangeRed2" :background "#EEE0DD"))))
 '(mew-highlight-mark-face-delete ((t (:foreground "firebrick" :background "#EEDDDD" :strikethru t))))
 '(mew-highlight-mark-face-multi ((t (:foreground "Purple" :background "#EEDDFF"))))
 '(mew-highlight-mark-face-refile ((t (:foreground "ForestGreen" :background "#DDEEDD"))))
 '(mew-highlight-mark-face-review ((t (:foreground "Blue" :background "#DDDDEE"))))
 '(mmm-default-submode-face ((t (:background "#002A03"))))
 '(mmm-delimiter-face ((t (:background "magenta4"))) t)
 '(mode-line ((t (:background "Gray75" :foreground "black"))))
 '(mode-line-buffer-id ((t (:foreground "blue4" :background "Grey75" :bold t))))
 '(modeline-mousable ((t (:foreground "firebrick" :background "Gray75"))))
 '(modeline-mousable-minor-mode ((t (:foreground "green4" :background "Gray75"))))
 '(paren-match ((t (:background "lavender"))))
 '(pointer ((t (:background "white"))))
 '(region ((((class color) (min-colors 88) (background dark)) (:background "#354A8C"))))
 '(right-margin ((t nil)))
 '(text-cursor ((t (:foreground "#EEEEEE" :background "darkgreen"))))
 '(widget-button-pressed-face ((((class color)) (:foreground "blue"))) t)
 '(zmacs-region ((t (:background "lightblue")))))
